#!/usr/bin/env zsh

# Executes all dotfiles exporting scripts.

if [[ -z "${IS_IMPORTED_DOTFILES_UTILS}" \
		|| "${IS_IMPORTED_DOTFILES_UTILS}" != true ]]; then
	source /dev/stdin <<< "$(curl -sL amrw.dev/scripts/dotfiles/dotfiles_utils)"
fi

URL="amrw.dev/scripts/dotfiles/export"
SCRIPT_NAMES=(
	dotfiles
	iterm
	karabiner
	vscode
)

for script in "${SCRIPT_NAMES[@]}"; do
	zsh <(curl -sL "${URL}/export_${script}")
done
