#!/usr/bin/env zsh

# Exports the user's dotfiles from their home directory.

if [[ -z "${IS_IMPORTED_DOTFILES_UTILS}" || "${IS_IMPORTED_DOTFILES_UTILS}" != true ]]; then
	source /dev/stdin <<< "$(curl -fsSL https://raw.githubusercontent.com/amrwc/amrwc.github.io/master/scripts/dotfiles/dotfiles_utils)"
fi

readonly BACKUP_PATH="${BACKUP_DIR_PATH}/dotfiles"
readonly SOURCE_PATH="${HOME}"
readonly DOTFILES_NAMES=(
	bash_profile
	bashrc
	gitconfig
	gitignore_global
	vimrc
	zshrc
)

mkdir -p "${BACKUP_PATH}"
for file in "${DOTFILES_NAMES[@]}"; do
	export_dotfile "${SOURCE_PATH}/.${file}" "${BACKUP_PATH}/${file}"
done
