#!/usr/bin/env zsh

# Executes all dotfiles exporting scripts.

if [[ -z "${IS_IMPORTED_DOTFILES_UTILS}" || "${IS_IMPORTED_DOTFILES_UTILS}" != true ]]; then
	source /dev/stdin <<< "$(curl -fsSL https://raw.githubusercontent.com/amrwc/amrwc.github.io/master/scripts/dotfiles/dotfiles_utils)"
fi

readonly URL="https://raw.githubusercontent.com/amrwc/amrwc.github.io/master/scripts/dotfiles/export"
readonly SCRIPT_NAMES=(
	dotfiles
	iterm
	karabiner
	vscode
)

for script in "${SCRIPT_NAMES[@]}"; do
	zsh <(curl -sL "${URL}/export_${script}")
done
