#!/usr/bin/env zsh

# Dotfiles utils
#
# Usage:
# source /dev/stdin <<< "$(curl -sL amrw.dev/scripts/dotfiles/dotfiles_utils)"

source /dev/stdin <<< "$(curl -sL amrw.dev/scripts/zsh_utils)"

######################
# CONSTANTS
######################

readonly BACKUP_DIR_PATH="${HOME}/Downloads/__dotfiles_backup"


######################
# FUNCTIONS
######################

# @param ${1} -- filename
# @param ${2} -- directory path
function backup_dotfile() {
	if [ -f "${2}/${1}" ]; then
		cp "${2}/${1}" "${2}/$(get_date_time)_${1}"
	fi
}

# @param ${1} -- source url; absolute URL to the file
# @param ${2} -- filename
# @param ${3} -- destination directory path
function import_dotfile() {
	backup_dotfile "${2}" "${3}"
	curl -sL "${1}" > "${3}/${2}"
}
