#!/usr/bin/env zsh

# Exports the user's dotfiles from their home directory.

if [[ -z "${IS_IMPORTED_DOTFILES_UTILS}" \
		|| "${IS_IMPORTED_DOTFILES_UTILS}" != true ]]; then
	source /dev/stdin <<< "$(curl -sL amrw.dev/scripts/dotfiles/dotfiles_utils)"
fi

BACKUP_PATH="${BACKUP_DIR_PATH}/dotfiles"
SOURCE_PATH="${HOME}"
DOTFILES_NAMES=(
	bash_profile
	bashrc
	gitconfig
	gitignore_global
	zshrc
)

mkdir -p "${BACKUP_PATH}"
for file in "${DOTFILES_NAMES[@]}"; do
	export_dotfile "${SOURCE_PATH}/.${file}" "${BACKUP_PATH}/${file}"
done
