#!/usr/bin/env zsh

# Exports Visual Studio Code's preferences

BACKUP_PATH="${HOME}/Downloads/__dotfiles_backup/vscode"
SOURCE_PATH="${HOME}/Library/Application Support/Code/User"

mkdir -p ${BACKUP_PATH}
cp "${SOURCE_PATH}/keybindings.json" ${BACKUP_PATH}
cp "${SOURCE_PATH}/settings.json" ${BACKUP_PATH}
