#!/usr/bin/env zsh

# Exports the user's dotfiles from their home directory.

source /dev/stdin <<< "$(curl -sL amrw.dev/scripts/dotfiles/dotfiles_utils)"

readonly BACKUP_PATH="${BACKUP_DIR_PATH}/dotfiles"
readonly SOURCE_PATH="${HOME}"
readonly DOTFILES_NAMES=(
	bash_profile
	bashrc
	gitconfig
	gitignore_global
	zshrc
)

mkdir -p "${BACKUP_PATH}"
for file in "${DOTFILES_NAMES[@]}"; do
	cp "${SOURCE_PATH}/.${file}" "${BACKUP_PATH}/${file}"
done
