#!/usr/bin/env zsh

# Executes all dotfiles exporting scripts.

readonly URL="amrw.dev/scripts/dotfiles"
readonly SCRIPT_NAMES=(
	dotfiles
	iterm
	karabiner
	vscode
)

for script in "${SCRIPT_NAMES[@]}"; do
	zsh <(curl -sL "${URL}/export_${script}")
done
