#!/usr/bin/env zsh

# Exports Karabiner-Elements' preferences.

source /dev/stdin <<< "$(curl -sL amrw.dev/scripts/dotfiles/dotfiles_utils)"

readonly BACKUP_PATH="${BACKUP_DIR_PATH}"
readonly SOURCE_PATH="${HOME}/.config/karabiner"

mkdir -p "${BACKUP_PATH}"
cp -r "${SOURCE_PATH}" "${BACKUP_PATH}"
