#!/usr/bin/env zsh

# Executes all dotfiles exporting scripts

URL="amrw.dev/scripts/dotfiles/"
SCRIPT_PREFIX="import_"
SCRIPTS=(
	dotfiles
	karabiner
	vscode
)

for script in "${SCRIPTS[@]}"
do
	bash <(curl -sL "${URL}${SCRIPT_PREFIX}${script}")
done

printf "Remember to set your 'git config --global' after the import, such as:\n"
printf "\tgit config --global user.<name, email, signingKey>\n"
printf "\tgit config --global commit.gpgSign true\n"
