#!/usr/bin/env bash

# A setup script for Mac computers.
#
# Usage:
# $ ./setup_mac [--development] [--communication] [--personal]
#
# @author amrwc
# @licence AGPL-3.0

{ # Ensures that the entire script is downloaded before execution

# https://formulae.brew.sh/formula/
readonly BREW_APPS=(
	autojump
	fd
	git
	gpg
	# pandoc
	thefuck
	# the_silver_searcher
	zsh
)
# https://formulae.brew.sh/cask/
readonly BREW_CASKS_COMMON=(
	# authy
	bitwarden
	# firefox
	flux
	karabiner-elements
	spotify
)
readonly BREW_CASKS_DEVELOPMENT=(
	ant
	# arduino
	# docker
	intellij-idea # Ultimate
	# intellij-idea-ce # Community Edition
	iterm2
	# java # OpenJDK
	# oracle-jdk
	# oracle-jdk-javadoc
	phpstorm
	postman
	ssh-tunnel-manager
	sublime-merge
	# virtualbox
	visual-studio-code
	# vagrant
	# vagrant-manager
	# vagrant-vmware-utility
	# wireshark
)
readonly BREW_CASKS_COMMUNICATION=(
	discord
	# protonmail-bridge
	signal
	# skype
	slack
	# thunderbird
	# whatsapp
	# zoomus
)
readonly BREW_CASKS_PERSONAL=(
	# calibre
	# libreoffice
	overkill # Kills iTunes/Apple Music in the background
	paintbrush
	# pdfsam-basic
	# protonvpn
	# the-unarchiver
	# tor-browser
	# transmission
	# veracrypt
	vlc
)

# Checks whether the element exists in the array.
# @param {array} arr quoted array
# @param {string} element
# @return {int} 0 if the array contains the element, 1 otherwise
# @see https://stackoverflow.com/a/8574392
function isElementIn() {
	local e element="${1}"
	shift
	for e; do [[ "${e}" == "${element}" ]] && return 0; done
	return 1
}

# Set up System Preferences
curl -sL https://amrw.dev/scripts/macos-preferences/setup_macos_preferences | bash -s

# Install Homebrew
command -v brew >/dev/null 2>&1 || \
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# Install brew applications
for app in "${BREW_APPS[@]}"; do
	brew install "${app}"
done

# Install common brew casks
for cask in "${BREW_CASKS_COMMON[@]}"; do
	brew cask install "${cask}"
done

# Install software development-related brew casks and software
if isElementIn "--development" "$@"; then
	for cask in "${BREW_CASKS_DEVELOPMENT[@]}"; do
		brew cask install "${cask}"
	done

	# Install nvm -- Node Version Manager
	if [[ ! -d "${HOME}/.nvm" || -z "$(ls -A "${HOME}/.nvm")" ]]; then
		curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.1/install.sh | bash
	fi

	# Install Node.js and npm
	nvm install 11 --lts --latest-npm
fi

# Install communication-related brew casks
if isElementIn "--communication" "$@"; then
	for cask in "${BREW_CASKS_COMMUNICATION[@]}"; do
		brew cask install "${cask}"
	done
fi

# Install personal brew casks
if isElementIn "--personal" "$@"; then
	for cask in "${BREW_CASKS_PERSONAL[@]}"; do
		brew cask install "${cask}"
	done
fi

# Import dotfiles
curl -fsSL https://raw.githubusercontent.com/amrwc/amrwc.github.io/master/scripts/dotfiles/import/import_all | bash -s

# Install Oh My Zsh
## NOTE: It should be executed last, because the Oh My Zsh installation script prompts the user whether they want to
## change the default shell to Zsh -- which is the case since that's what the plugin is for -- thus breaking the
## script's execution.
if [[ ! -d "${HOME}/.oh-my-zsh" || -z "$(ls -A "${HOME}/.oh-my-zsh")" ]]; then
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
fi

} # Ensures that the entire script is downloaded before execution
