#!/usr/bin/env bash

# Make a backup of root preferences before and after changes are made.
#
# Usage:
# ./make_backup_root [before/after]

source constants

if [ -z ${1} ]; then
	read -p "Is it a backup (${COLOUR_MAGENTA}b${TEXT_RESET})efore or (${COLOUR_MAGENTA}a${TEXT_RESET})fter the change was made? (${COLOUR_MAGENTA}before${TEXT_RESET}/${COLOUR_MAGENTA}after${TEXT_RESET}): " before_or_after
else
	before_or_after=${1}
fi

case ${before_or_after:0:1} in
	b|B|before|Before|BEFORE )
		destination="${PATH_BEFORE}_ROOT"
	;;
	a|A|after|After|AFTER )
		destination="${PATH_AFTER}_ROOT"
	;;
	* )
		printf "${COLOUR_RED}No option was chosen, therefore no backups were made.${TEXT_RESET}\n"
		exit 1
	;;
esac

mkdir -p ${PATH_PREFERENCES_BACKUP} && sudo cp -r /Library/Preferences/ ${destination}
