#!/usr/bin/env bash

source constants

before="${PATH_PREFERENCES_BACKUP}/before"
after="${PATH_PREFERENCES_BACKUP}/after"

if [ -z ${1} ]; then
	read -p "What is the domain (the plist config file)? " domain_name
else
	domain_name=${1}
fi

if [ -z ${2} ]; then
	read -p "What diff tool would you like to use? (${COLOUR_MAGENTA}diff${TEXT_RESET}/${COLOUR_MAGENTA}code${TEXT_RESET}): " diff_tool
else
	diff_tool=${2}
fi

case ${diff_tool:0:1} in
	diff|DIFF|Diff|d|D )
		diff_tool="diff"
	;;
	code|CODE|Code|c|C )
		diff_tool="code --diff"
	;;
	* )
		printf "${COLOUR_RED}Diff tool name not recognised; exiting.${TEXT_RESET}\n"
		exit 1
	;;
esac

plutil -convert xml1 -o /dev/stdout ${PATH_BEFORE}/${domain_name} > ${before}
plutil -convert xml1 -o /dev/stdout ${PATH_AFTER}/${domain_name} > ${after}
${diff_tool} ${before} ${after}
