#!/usr/bin/env zsh

# Imports all dotfiles into the user's home directory.

# Current date and time in 'YYYY-MM-DD_HH:MM:SS' format.
CURRENT_DATE_TIME=$(date +"%Y-%m-%d_%T")
DOTFILES_URL="https://raw.githubusercontent.com/amrwc/amrwc.github.io/master/dotfiles/dotfiles"
DOTFILES=(
	bash_profile
	bashrc
	gitconfig
	gitignore_global
	vimrc
	zshrc
)

function import_dotfile() {
	local name="${1}"
	local file_path="${HOME}/.${name}"
	# If the dotfile exists...
	if [ -f "${file_path}" ]; then
		# ...make its dated copy before overwriting it.
		cp "${file_path}" "${file_path}_${CURRENT_DATE_TIME}"
	fi
	curl -sL "${DOTFILES_URL}/${name}" > "${file_path}"
}

for file in "${DOTFILES[@]}"
do
	import_dotfile "${file}"
done
