#!/usr/bin/env zsh

# Executes all dotfiles importing scripts

readonly URL="https://raw.githubusercontent.com/amrwc/amrwc.github.io/master/scripts/dotfiles/import"
readonly SCRIPT_NAMES=(
	dotfiles
	iterm
	karabiner
	vscode
)

for script in "${SCRIPT_NAMES[@]}"; do
	zsh <(curl -sL "${URL}/import_${script}")
done

printf "Remember to set your 'git config --global' after the import, such as:\n"
printf "\tgit config --global user.<name, email, signingKey>\n"
printf "\tgit config --global commit.gpgSign true\n"
