#!/usr/bin/env zsh

# Imports Karabiner-Elements' preferences

# Current date and time in 'YYYY-MM-DD_HH:MM:SS' format.
CURRENT_DATE_TIME=$(date +"%Y-%m-%d_%T")
DOTFILES_URL="https://raw.githubusercontent.com/amrwc/amrwc.github.io/master/dotfiles/karabiner"
DESTINATION_PATH="${HOME}/.config/karabiner"

function import_dotfile() {
	local file_name="${1}"
	local file_path="${DESTINATION_PATH}/${file_name}"
	# If the file exists...
	if [ -f "${file_path}" ]; then
		# ...make its dated copy before overwriting it.
		local backup_file_path="${DESTINATION_PATH}/${CURRENT_DATE_TIME}_${file_name}"
		cp "${file_path}" "${backup_file_path}"
	fi
	curl -sL "${DOTFILES_URL}/${file_name}" > "${file_path}"
}

mkdir -p "${DESTINATION_PATH}"
import_dotfile "karabiner.json"
