#!/usr/bin/env zsh

# Imports iTerm2's preferences
#
# Usage:
# zsh <(curl -sL amrw.dev/scripts/dotfiles/import_iterm)

if [[ -z "${IS_IMPORTED_DOTFILES_UTILS}" || "${IS_IMPORTED_DOTFILES_UTILS}" != true ]]; then
	source /dev/stdin <<< "$(curl -fsSL https://raw.githubusercontent.com/amrwc/amrwc.github.io/master/scripts/dotfiles/dotfiles_utils)"
fi

SOURCE_URL="https://raw.githubusercontent.com/amrwc/amrwc.github.io/master/scripts/dotfiles/iterm2/com.googlecode.iterm2.xml"
SOURCE_FILENAME="com.googlecode.iterm2.xml"
DESTINATION_DIR_PATH="${HOME}/Library/Preferences"
FINAL_FILENAME="com.googlecode.iterm2.plist"
PLIST_NAME="com.googlecode.iterm2"

println_colour "yellow" "Quitting iTerm" && killall "iTerm2"
backup_dotfile "${FINAL_FILENAME}" "${DESTINATION_DIR_PATH}" \
	&& println_colour "yellow" "Backed up the existing preferences"
defaults delete "${PLIST_NAME}" \
	&& println_colour "yellow" "Deleted old preferences"
import_dotfile "${SOURCE_URL}" "${SOURCE_FILENAME}" "${DESTINATION_DIR_PATH}" \
	&& println_colour "yellow" "Deleted old preferences"

cd "${DESTINATION_DIR_PATH}"
# Convert the XML source file to binary (.plist)
plutil -convert xml1 "${SOURCE_FILENAME}" -o "${FINAL_FILENAME}"
# Load the preferences
defaults read "${PLIST_NAME}" > /dev/null \
	&& println_colour "green" "Applied new preferences"

println_colour "blue" "NOTE: You may have to restart iTerm for the changes to take effect."
