#!/usr/bin/env bash

# NOTE: THIS SCRIPT HASN'T BEEN TESTED BY RUNNING THE ENTIRETY OF IT -- ONLY
#       THE INDIVIDUAL INSTRUCTIONS HAVE BEEN RUN. BE ESPECIALLY MINDFUL OF THE
#       LINES CHANGING THE .GlobalPreferences.plist file.
# NOTE: THE COMMENTED OUT INSTRUCTIONS MANIPULATING THE AFOREMENTIONED FILE
#       MUST BE TESTED ON A CLEAN SETUP TO ENSURE THE DESIRED EFFECTS.
#
# The script adjusts macOS's System Preferences to my liking. The idea to
# write the script came from having to set up a MacBook from scratch a few
# times in a span of a month. The first time, I documented each setting changed
# inside of System Preferences app so that I could replicate them at a later.
# The second time I started looking into automating the process. The obvious,
# default solution would be to use Time Machine; it is, however, quite an
# overkill to store the entire system's state, rather than just the
# configuration. Also, using Time Machine requires to have the perfect vanilla
# setup when the 'image' is taken, otherwise the backup will end up with
# software that may be redundant on another computer the image is placed on.
#
# Usage:
# curl -sL amrw.dev/scripts/macos-preferences/__macos_preferences | bash -s

# Quit System Preferences.app to prevent it from overriding the changes
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Backup configuration files
## Current date and time in 'YYYY-MM-DD_HH:MM:SS' format.
CURRENT_DATE_TIME=$(date +"%Y-%m-%d_%T")
mkdir -p ~/Downloads/__BACKUP_CONFIGS && cp -r ~/Library/Preferences/ ${_}/Preferences_${CURRENT_DATE_TIME}

# Security & Privacy
## disable `Advanced…/Log out after N minutes of inactivity` (NOTE: isn't it default and doesn't have to be changed?)
# sudo defaults write /Library/Preferences/.GlobalPreferences com.apple.autologout.AutoLogOutDelay -int 0
# sudo defaults write /Library/Preferences/.GlobalPreferences com.apple.securitypref.logoutvalue -int 0

# Dock
# bash <(curl -sL https://amrw.dev/scripts/macos-preferences/dock) # Run from the server
# ~/Downloads/__macos-preferences/dock # Run from a local directory

# Mission Control
# bash <(curl -sL https://amrw.dev/scripts/macos-preferences/mission_control) # Run from the server
# ~/Downloads/__macos-preferences/mission_control # Run from a local directory

# Language & Region
# bash <(curl -sL https://amrw.dev/scripts/macos-preferences/language_and_region) # Run from the server
# ~/Downloads/__macos-preferences/language_and_region # Run from a local directory

# Keyboard
# bash <(curl -sL https://amrw.dev/scripts/macos-preferences/keyboard) # Run from the server
# ~/Downloads/__macos-preferences/keyboard # Run from a local directory

# Finder
## Show file extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Misc
defaults write NSGlobalDomain NSAutomaticTextCompletionEnabled -bool false
defaults write NSGlobalDomain NSLinguisticDataAssetsRequested -array '(en_GB, pl_GB, nb_GB, de_GB)'
defaults write NSGlobalDomain WebAutomaticSpellingCorrectionEnabled -bool false

# Kill affected apps
APPS=(
  Dock
  Finder
  SystemUIServer
)
for app in "${APPS[@]}"
do
  killall "${app}" > /dev/null 2>&1
done

# Done
echo "Done. Note that some of these changes require a logout/restart to take effect."
