#!/usr/bin/env bash

# Keyboard

## Press and hold repeats a key rather than showing options
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

## `Key Repeat` (rate)
### minimum: 1, off: 300000, slow: 120, fast: 2
defaults write NSGlobalDomain KeyRepeat -int 2

## `Delay Until Repeat` (ms)
### long: 120, short: 15
### Anything below 15 causes unintentional repeating
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Text

## disable `Correct spelling automatically`
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

## disable `Capitalize words automatically`
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

## disable `Add period with double-space`
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

## `Spelling`: Automatic by Language
defaults write NSGlobalDomain NSSpellCheckerAutomaticallyIdentifiesLanguages -bool true

## disable `Use smart quotes and dashes`
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

## set Double Quites and Single Quotes
defaults write NSGlobalDomain NSUserQuotesArray -array '"\""' '"\""' '"'\''"' '"'\''"'

# Shortcuts

## Input Sources
### disable `Select the previous input source`
### TODO: Test it, since it doesn't seem to work.
###       What to restart? Finder is not it.
###       Try setting it in /Library/Preferences (the root Preferences)
# defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 60 "{enabled = 0; value = {parameters = (65535, 49, 1048576); type = 'standard';};}"
/usr/libexec/PlistBuddy -c 'Set :AppleSymbolicHotKeys:60:enabled 0' ~/Library/Preferences/com.apple.symbolichotkeys.plist

## `App Shortcuts`
### Modifier key legend:
### ^: ⌃  Control
### ~: ⌥  Option
### $: ⇧  Shift
### @: ⌘  Command
### \033: Nested Option Delimiter
### nil:  no shortcut
### TODO: This doesn't seem to take effect in the System Preferences
defaults delete NSGlobalDomain NSUserKeyEquivalents
defaults write NSGlobalDomain NSUserKeyEquivalents -dict-add "Copy" -string "@;"
defaults write NSGlobalDomain NSUserKeyEquivalents -dict-add "Paste" -string "@'"

## `Full Keyboard Access`: All controls -- press Tab to move keyboard focus between:
### Text boxes and lists only: 1
### All controls: 3
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Input Sources
# TODO: This doesn't seem to take effect in the System Preferences

##  Set `Polish - Pro` and `British - PC` as available Input Sources
## NOTE: The dictionary below outputs 30788 as a string. A workaround is to use
##       the PlistBuddy method beneath, despite its verbosity.
# defaults write com.apple.HIToolbox AppleEnabledInputSources -array '{InputSourceKind = "Keyboard Layout"; "KeyboardLayout ID" = 30788; "KeyboardLayout Name" = "Polish Pro";}' '{InputSourceKind = "Keyboard Layout"; "KeyboardLayout ID" = 250; "KeyboardLayout Name" = "British-PC";}'
/usr/libexec/PlistBuddy -c 'Delete :AppleEnabledInputSources' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleEnabledInputSources array' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleEnabledInputSources:0 dict' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleEnabledInputSources:0:InputSourceKind string "Keyboard Layout"' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleEnabledInputSources:0:"KeyboardLayout ID" integer 30788' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleEnabledInputSources:0:"KeyboardLayout Name" string "Polish Pro"' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleEnabledInputSources:1 dict' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleEnabledInputSources:1:InputSourceKind string "Keyboard Layout"' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleEnabledInputSources:1:"KeyboardLayout ID" integer 250' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleEnabledInputSources:1:"KeyboardLayout Name" string "British-PC"' ~/Library/Preferences/com.apple.HIToolbox.plist

## Select `Polish - Pro` to be active
defaults write com.apple.HIToolbox AppleCurrentKeyboardLayoutInputSourceID -string "com.apple.keylayout.PolishPro"

# defaults write com.apple.HIToolbox AppleSelectedInputSources -array '{InputSourceKind = "Keyboard Layout"; "KeyboardLayout ID" = 30788; "KeyboardLayout Name" = "Polish Pro";}'
/usr/libexec/PlistBuddy -c 'Delete :AppleSelectedInputSources' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleSelectedInputSources array' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleSelectedInputSources:0 dict' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleSelectedInputSources:0:InputSourceKind string "Keyboard Layout"' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleSelectedInputSources:0:"KeyboardLayout ID" integer 30788' ~/Library/Preferences/com.apple.HIToolbox.plist
/usr/libexec/PlistBuddy -c 'Add :AppleSelectedInputSources:0:"KeyboardLayout Name" string "Polish Pro"' ~/Library/Preferences/com.apple.HIToolbox.plist
