#!/usr/bin/env bash

# Keyboard

## Press and hold repeats a key rather than showing options
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool false

## `Key Repeat` (rate)
### minimum: 1, off: 300000, slow: 120, fast: 2
defaults write NSGlobalDomain KeyRepeat -int 1

## `Delay Until Repeat` (ms)
### long: 120, short: 15
defaults write NSGlobalDomain InitialKeyRepeat -int 10

# Text

## disable `Correct spelling automatically`
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

## disable `Capitalize words automatically`
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

## disable `Add period with double-space`
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

## `Spelling`: Automatic by Language
defaults write NSGlobalDomain NSSpellCheckerAutomaticallyIdentifiesLanguages -bool true

## disable `Use smart quotes and dashes`
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

## set Double Quites and Single Quotes
defaults write NSGlobalDomain NSUserQuotesArray -array '"\""' '"\""' '"'\''"' '"'\''"'

# Shortcuts

## Input Sources
### disable `Select the previous input source`
### TODO: Test it, since it doesn't seem to work.
###       What to restart? Finder is not it.
###       Try setting it in /Library/Preferences (the root Preferences)
# defaults write com.apple.symbolichotkeys AppleSymbolicHotKeys -dict-add 60 "{enabled = 0; value = {parameters = (65535, 49, 1048576); type = 'standard';};}"
# /usr/libexec/PlistBuddy -c 'Set :AppleSymbolicHotKeys:60:enabled 0' ~/Library/Preferences/com.apple.symbolichotkeys.plist

## `App Shortcuts`
### Modifier key legend:
### ^: ⌃  Control
### ~: ⌥  Option
### $: ⇧  Shift
### @: ⌘  Command
### \033: Nested Option Delimiter
### nil:  no shortcut
### TODO: This doesn't seem to take effect in the System Preferences
defaults delete NSGlobalDomain NSUserKeyEquivalents
defaults write NSGlobalDomain NSUserKeyEquivalents -dict-add "Copy" -string "@;"
defaults write NSGlobalDomain NSUserKeyEquivalents -dict-add "Paste" -string "@'"

## `Full Keyboard Access`: All controls -- press Tab to move keyboard focus between:
### Text boxes and lists only: 1
### All controls: 3
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3
