#!/usr/bin/env bash

# Language & Region

## Set system language(s)
defaults write .GlobalPreferences AppleLocale -string en_GB
defaults write .GlobalPreferences AppleLanguages '(en-GB, pl-GB)'
defaults write .GlobalPreferences AppleICUForce12HourTime -bool true
defaults write .GlobalPreferences AppleTemperatureUnit -string Celsius
defaults write .GlobalPreferences AppleMeasurementUnits -string Centimeters
defaults write .GlobalPreferences AppleMetricUnits -bool true
