#!/usr/bin/env bash

# Language & Region

## Set system language(s)
defaults write NSGlobalDomain AppleLocale -string en_GB
defaults write NSGlobalDomain AppleLanguages '(en-GB, pl-GB)'
defaults write NSGlobalDomain AppleICUForce12HourTime -bool true
defaults write NSGlobalDomain AppleTemperatureUnit -string Celsius
defaults write NSGlobalDomain AppleMeasurementUnits -string Centimeters
defaults write NSGlobalDomain AppleMetricUnits -bool true
