#!/usr/bin/env bash

# Set up macOS Preferences
#
# An automation of the machine setup process.
#
# The idea for writing the script came from having to set up a MacBook from scratch a few times in a span of a month.
# The obvious, default solution would be to use Time Machine; it is, however, quite an overkill to store the entire
# system's state, rather than just the configuration.
#
# Usage:
# $ ./setup_macos_preferences
#
# Or without having the script available locally:
# $ curl -sL https://amrw.dev/scripts/macos-preferences/setup_macos_preferences | bash -s

# Ask for the administrator password upfront
sudo -v

# Quit System Preferences.app to prevent it from overriding the changes
osascript -e 'tell application "System Preferences" to quit'

# Backup configuration files
## Current date and time in 'YYYY-MM-DD_HH:MM:SS' format.
CURRENT_DATE_TIME=$(date +"%Y-%m-%d_%T")
BACKUP_LOCATION="~/Downloads/__BACKUP_CONFIGS"
mkdir -p "${BACKUP_LOCATION}" \
	&& sudo cp -r ~/Library/Preferences "${BACKUP_LOCATION}/Preferences_${CURRENT_DATE_TIME}"

# Finder
## Show file extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Miscellaneous
defaults write NSGlobalDomain NSAutomaticTextCompletionEnabled -bool false
defaults write NSGlobalDomain NSLinguisticDataAssetsRequested -array 'pl' 'pl_GB' 'en' 'en_GB' 'de' 'de_GB'
defaults write NSGlobalDomain WebAutomaticSpellingCorrectionEnabled -bool false

bash <(curl -sL https://amrw.dev/scripts/macos-preferences/dock)
bash <(curl -sL https://amrw.dev/scripts/macos-preferences/mission_control)
bash <(curl -sL https://amrw.dev/scripts/macos-preferences/language_and_region)
bash <(curl -sL https://amrw.dev/scripts/macos-preferences/keyboard)

# Kill affected apps
APPS=(
	Dock
	Finder
	SystemUIServer
)
for app in "${APPS[@]}"
do
	killall "${app}" > /dev/null 2>&1
done

# Done
echo "Done. Note that some of these changes require a logout/restart to take effect."
