#!/usr/bin/env bash

read -p "user.name (current: '"$(git config user.name)"'): " user_name
if [ -n "$user_name" ]; then
	git config user.name "$user_name"
fi

read -p "user.email (current: '"$(git config user.email)"'): " user_email
if [ -n "$user_email" ]; then
	git config user.email "$user_email"
fi

read -p "commit.gpgSign [true/false] (current: '"$(git config commit.gpgSign)"'): " gpg_sign
if [ -n "$gpg_sign" ]; then
	git config commit.gpgSign "$gpg_sign"
fi

printf "\n\n"
gpg --list-secret-keys --keyid-format LONG
printf "From the keys listed above pick one and paste its SSB's part after 'rsa4096/'\n"
read -p "(current: '"$(git config user.signingKey)"'): " user_signing_key
if [ -n "$user_signing_key" ]; then
	git config user.signingKey "$user_signing_key"
fi
